### ISSUE TITLE
Remover referências ao likes do topics

### ISSUE THREAD

**Issue by felipeconti** [felipeconti/coffeeandcode#12]

**Comment by afucher** [comment]
Poderia explicar melhor?

**Comment by felipeconti** [comment]
Faltou tirar a propriedade likes da collection Topics, e ver como fazer para filtrar e ordenar os registros.
Já que isso era feito com essa coluna.

Alguma ideia?

**Comment by afucher** [comment]
Mas não íamos manter? Entendi que íamos atualizar, igual fazíamos no outro...

**Comment by felipeconti** [comment]
Feito!
